// Auth
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_EXPIRES_IN = 'SET_EXPIRES_IN'
export const SET_IS_AUTHED = 'SET_IS_AUTHED'

// User
export const GET_USER = 'GET_USER'

// Song
export const GET_GENRE_SEEDS = 'GET_GENRE_SEEDS'
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS'
export const GET_SONGS = 'GET_SONGS'
export const GET_RECENTS = 'GET_RECENTS'

// Playlist
export const GET_USER_PLAYLIST = 'GET_USER_PLAYLIST'
export const GET_PLAYLIST_BY_ID = 'GET_PLAYLIST_BY_ID'
export const GET_PLAYLISTS_LIST = 'GET_PLAYLISTS_LIST'
export const CLEAR_PLAYLIST_BY_ID = 'CLEAR_PLAYLIST_BY_ID'
export const REMOVE_ITEMS_FROM_PLAYLIST = 'REMOVE_ITEMS_FROM_PLAYLIST'
